set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(PRISM_AARCH64_CROSS_PREFIX "aarch64-linux-gnu-" CACHE STRING
  "Prefix of the Linux AArch64 cross compiler")
set(CMAKE_C_COMPILER "${PRISM_AARCH64_CROSS_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${PRISM_AARCH64_CROSS_PREFIX}g++")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
